Scan barcode and request product from api
OmarBafagih/Health-Inspect pull request #6
Opened 2022-06-24 22:02 UTC by OmarBafagih

Closes #4

2022-06-24 22:17 UTC, nickshekelle requested changes
looks good but please address the comment

2022-06-24 22:17 UTC, nickshekelle commented on app/src/main/java/com/example/healthinspector/Fragments/ScanFlow/ScanFragment.java
> +                                    bundle.putParcelable("scannedProduct", Parcels.wrap(scannedProduct));
store this "scannedProduct" in a constant so you can access it in both fragments. It is a good practice to have all raw strings like this defined in one place

2022-06-24 22:23 UTC, nickshekelle requested changes

2022-06-24 22:23 UTC, nickshekelle commented on app/src/main/java/com/example/healthinspector/Fragments/ScanFlow/ProductDetailsFragment.java
> +        // Inflate the layout for this fragment
why do we need this comment? i think the code below is pretty self explanatory

2022-06-24 22:23 UTC, nickshekelle commented on app/src/main/java/com/example/healthinspector/Fragments/ScanFlow/ScanFragment.java
> +                        JsonObjectRequest objectRequest = new JsonObjectRequest(Request.Method.GET, "https://world.openfoodfacts.org/api/v2/product/7622210449283", null, new Response.Listener<JSONObj
please store this URL in a constant somewhere

2022-06-24 22:23 UTC, nickshekelle commented on app/src/main/java/com/example/healthinspector/Fragments/ScanFlow/ScanFragment.java
> +                                    //creating a scannedProduct object for to wrap with
please get rid of theses comments. Comments in code should really only be for explaining something really complex or unintuitive.

2022-06-24 22:23 UTC, nickshekelle commented on app/src/main/java/com/example/healthinspector/Fragments/ScanFlow/ScanFragment.java
> +                                        ingredientsAnalysis.set(i, analysis);
I'm almost certain there is a built in library to do this

2022-06-24 22:23 UTC, nickshekelle commented on app/src/main/java/com/example/healthinspector/Fragments/ScanFlow/ScanFragment.java
> +                                    JSONArray ingredientsAnalysisJSON = response.getJSONObject("product").getJSONArray("ingredients_analysis_tags");
lots of raw strings, please store in constants

2022-06-24 22:23 UTC, nickshekelle commented on app/src/main/java/com/example/healthinspector/Fragments/ScanFlow/ScanFragment.java
> +                                    JSONObject nutrientLevelsJSON = response.getJSONObject("product").getJSONObject("nutrient_levels");
more raw strings

2022-06-24 22:24 UTC, nickshekelle approved these changes
this looks good to me but please remove these extraneous comments before merging

2022-06-24 22:25 UTC, nickshekelle requested changes

2022-06-24 22:25 UTC, nickshekelle commented on app/src/main/java/com/example/healthinspector/Fragments/ScanFragment.java
>          // Inflate the layout for this fragment
please remove extraneous comments like this

2022-06-24 22:29 UTC, nickshekelle requested changes
please address all my comments

2022-06-24 22:29 UTC, nickshekelle commented on app/src/main/java/com/example/healthinspector/Fragments/ScanFragment.java
> +                        Toast.makeText(getContext(), result.getText(), Toast.LENGTH_SHORT).show();
is there a `requireContext()` function? I recommend to avoid null pointer exceptions

2022-06-24 22:29 UTC, nickshekelle commented on app/src/main/java/com/example/healthinspector/Fragments/SearchFragment.java
> +                //user did not allow Camera permissions
please remove comments

2022-06-24 22:29 UTC, nickshekelle commented on app/src/main/java/com/example/healthinspector/Fragments/ScanFragment.java
> +                                    Log.i(TAG, response.getJSONObject("product").getString("product_name"));
no raw strings please

2022-06-24 22:29 UTC, nickshekelle commented on app/src/main/java/com/example/healthinspector/Fragments/ScanFlow/ScanFragment.java
> +                                    //creating a scannedProduct object to wrap with Parceler and put pas to the next fragment
no need for all these comments

2022-06-24 22:44 UTC, Anish2607 commented
Make sure to add a summary that describes the changes and included a video showing the changes

2022-06-27 17:51 UTC, merged

2022-06-29 04:47 UTC, Anish2607 reviewed
This looks great overall! Good job on getting the scanning working and querying the API with the scanned barcode

2022-06-29 04:47 UTC, Anish2607 commented on app/src/main/java/com/example/healthinspector/Fragments/ScanFlow/ScanFragment.java
> +    private HashMap<Integer, String> novaGroups = new HashMap<>();
Rename to novaGroupsMap cause it's easy to get confused between novaGroup's' and novaGroup

2022-06-29 04:47 UTC, Anish2607 commented on app/src/main/java/com/example/healthinspector/Fragments/ScanFlow/ScanFragment.java
> +        novaGroups.put(4,"ultra processed food or drink product");
these can be moved to strings.xml

2022-06-29 04:47 UTC, Anish2607 commented on app/src/main/java/com/example/healthinspector/Fragments/ScanFlow/ScanFragment.java
> +        View view = binding.getRoot();
this doesn't seemed to be used until the end of the function so we can get it there

2022-06-29 04:47 UTC, Anish2607 commented on app/src/main/java/com/example/healthinspector/Fragments/ScanFlow/ScanFragment.java
> +        codeScannerView = new CodeScanner(getActivity(), scannerView);
nit: we already have the activity so we dont need to call "getActivity" again

2022-06-29 04:47 UTC, Anish2607 commented on app/src/main/java/com/example/healthinspector/Fragments/ScanFlow/ScanFragment.java
> +                        JsonObjectRequest objectRequest = new JsonObjectRequest(Request.Method.GET, getString(R.string.URL) + result.getText(), null, new Response.Listener<JSONObject>() {
we can move this to a separate function so it's easier to read. Additionally, we can add some top level comments describing how we are parsing and even include a link to sample JSON response that is being parsed

2022-06-29 04:47 UTC, Anish2607 commented on app/src/main/java/com/example/healthinspector/Fragments/ScanFlow/ScanFragment.java
> +                            }
we should show a toast a user even something goes wrong. So they know what to do next

2022-06-29 04:47 UTC, Anish2607 commented on app/src/main/java/com/example/healthinspector/Fragments/SearchFragment.java
> +            }
I dont think this needs to be a class variable. We can just move this block of code to the onclick

2022-06-29 04:47 UTC, Anish2607 commented on app/src/main/res/values/strings.xml
> +    <string name="nutrient_levels">nutrient_levels</string>
This is great!!

2022-06-29 04:47 UTC, Anish2607 commented on app/src/main/res/layout/fragment_search.xml
> +            android:id="@+id/scanIconImageView"
good changes!

2022-06-29 16:41 UTC, OmarBafagih commented on app/src/main/java/com/example/healthinspector/Fragments/SearchFragment.java
> +            }
I tried to do this and get this error: attempting to registerForActivityResult after being created. Fragments must call registerForActivityResult() before they are created (i.e. initialization, onAttach(), or onCreate()).

Seems like even if I move my onClick to onCreate and try to registerForActivityResult, it still gives the error because it reaches the end of the onCreate before the onClick is triggered

2022-06-29 20:06 UTC, Anish2607 commented on app/src/main/java/com/example/healthinspector/Fragments/SearchFragment.java
> +            }
Ahh I see, interesting. This is fine then!